version: '3'

services:
  hadoop-master:
    build: ./docker-hadoop-master
    container_name: "hadoop-master"
    hostname: hadoop-master
    networks:
      - hadoop
    volumes:
      - ~/docker-data/hdp.m1/:/opt/data/
    ports:
      - "50070:50070"
      - "8080:8080"
      - "8085:8085"
      - "9090:9090"
      - "9095:9095"
      - "8020:8020"
      - "8088:8088"   
  hadoop-slave1:
    build: ./docker-hadoop
    container_name: "hadoop-slave1"
    hostname: hadoop-slave1
    networks:
      - hadoop
    depends_on:
      - hadoop-master
    volumes:
      - /opt/data/ ~/docker-data/hdp.s1/

  hadoop-slave2:
    build: ./docker-hadoop
    container_name: "hadoop-slave2"
    hostname: hadoop-slave2
    networks:
      - hadoop
    depends_on:
      - hadoop-master
    volumes:
      - /opt/data/ ~/docker-data/hdp.s2/

networks:
  hadoop:
    external: true           